services:
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: sh -c "pnpm prisma migrate deploy --schema apps/auth/prisma/schema.prisma && pnpm prisma generate --schema apps/auth/prisma/schema.prisma && pnpm run start:dev auth"
    env_file:
      - ./apps/auth/.env
    ports:
      - '3010:3010'
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
      - rabbitmq

  profile:
    build:
      context: .
      dockerfile: ./apps/profile/Dockerfile
      target: development
    command: pnpm run start:dev profile
    env_file:
      - ./apps/profile/.env
    ports:
      - '3015:3015'
    volumes:
      - .:/usr/src/app
    depends_on:
      - auth

  metrics:
    build:
      context: .
      dockerfile: ./apps/metrics/Dockerfile
      target: development
    command: sh -c "pnpm prisma migrate deploy --schema apps/metrics/prisma/schema.prisma && pnpm prisma generate --schema apps/metrics/prisma/schema.prisma && pnpm run start:dev metrics"
    env_file:
      - ./apps/metrics/.env
    ports:
      - '3020:3020'
    volumes:
      - .:/usr/src/app
    depends_on:
      - auth
      - rabbitmq

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: themainuserforpg
      POSTGRES_PASSWORD: hahD9GDpHpRALJt4ds5V
    ports:
      - '5433:5432'

  rabbitmq:
    image: rabbitmq:3.13-management
    environment:
      RABBITMQ_DEFAULT_USER: themainuserforrmq
      RABBITMQ_DEFAULT_PASS: hhrySFYDdbgVSSHBD12HSa
    ports:
      - '5672:5672'
      - '15672:15672'
