services:
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: sh -c "pnpm prisma migrate deploy --schema apps/auth/prisma/schema.prisma && pnpm prisma generate --schema apps/auth/prisma/schema.prisma && pnpm run start:dev auth"
    env_file:
      - ./apps/auth/.env
    ports:
      - '3010:3010'
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: themainuserforpg
      POSTGRES_PASSWORD: hahD9GDpHpRALJt4ds5V
      POSTGRES_DB: auth
    ports:
      - '5433:5432'
